[project]
name = "lambdasoc"
version = "0.1.0"
description = "A framework for building SoCs with Amaranth"
authors = [
    {name = "LambdaConcept", email = "contact@lambdaconcept.com"},
]
dependencies = [
    "jinja2 >= 3.0",
    "amaranth >= 0.5, < 0.6",
    "amaranth-soc",
    "amaranth-stdio",
    "amaranth-boards",
    "minerva",

    "migen @ git+https://github.com/m-labs/migen@3ffd64c9b47619bd6689b44f29a8ed7c74365f14",
    "litex @ git+https://github.com/enjoy-digital/litex@f9f1b8e25db6d6db1aa47a135a5f898c433d516e",
    "litedram @ git+https://github.com/enjoy-digital/litedram@83d18f48c7f7590096ddb35d669836d7abb3be6f",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "BSD"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
